In [ ]:
!nvidia-smi

Sun Sep  3 08:41:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
## Get tensor back as Python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7 ,8, 9]],])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Creare a random tensors of size (3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.3184, 0.8634, 0.3073, 0.6531],
         [0.4146, 0.8209, 0.9483, 0.6328],
         [0.8422, 0.8989, 0.8897, 0.3794]],

        [[0.3941, 0.7750, 0.3953, 0.1751],
         [0.0035, 0.8312, 0.2839, 0.4412],
         [0.8415, 0.9011, 0.4793, 0.3309]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# height, width, color channel (R, G, B)
rando_image_size_tensor = torch.rand(size=(3, 224, 224))
rando_image_size_tensor.shape, rando_image_size_tensor.ndim,

(torch.Size([3, 224, 224]), 3)

In [ ]:
rando_image_size_tensor

tensor([[[0.0709, 0.6132, 0.9874,  ..., 0.0535, 0.9197, 0.5555],
         [0.1053, 0.2874, 0.4113,  ..., 0.1398, 0.5956, 0.2503],
         [0.3169, 0.3554, 0.3688,  ..., 0.8632, 0.0252, 0.6863],
         ...,
         [0.5218, 0.4469, 0.9216,  ..., 0.7543, 0.2883, 0.2656],
         [0.2145, 0.3262, 0.0181,  ..., 0.9838, 0.6394, 0.1331],
         [0.9567, 0.0136, 0.2499,  ..., 0.4914, 0.0696, 0.5679]],

        [[0.7834, 0.0577, 0.7132,  ..., 0.7681, 0.4635, 0.7231],
         [0.9498, 0.3336, 0.0995,  ..., 0.4916, 0.0794, 0.1180],
         [0.6782, 0.0749, 0.2449,  ..., 0.8179, 0.6958, 0.3108],
         ...,
         [0.9810, 0.8854, 0.4408,  ..., 0.4182, 0.2694, 0.7297],
         [0.4408, 0.6574, 0.5609,  ..., 0.5939, 0.0545, 0.1457],
         [0.2079, 0.5942, 0.9266,  ..., 0.3755, 0.9945, 0.0295]],

        [[0.6459, 0.3623, 0.5003,  ..., 0.9844, 0.3053, 0.6366],
         [0.8160, 0.2307, 0.5903,  ..., 0.3185, 0.4889, 0.9353],
         [0.0770, 0.6481, 0.0287,  ..., 0.4656, 0.5981, 0.

In [ ]:
# torch.rand(size=(3, 3))
torch.rand((3, 3))

tensor([[0.2978, 0.6152, 0.4035],
        [0.6978, 0.4384, 0.8953],
        [0.1643, 0.8144, 0.5507]])

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Create range of tensor and tensors-like

In [ ]:
ranges = torch.arange(0, 9, 1)
ranges

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#  Create tensors like
# ten_zeros = ranges*torch.zeros(size=(1, 9))
ten_zeros = torch.zeros_like(input=ranges)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes - Tensor attribute

Aside from ***shape issues*** (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are ***datatype*** and ***device issues.***

1. Tensors not right datatype -> tensor.dtype
2. Tensors not right shape -> tensor.shape
3. Tensors not on the right device -> tensor.device

In [ ]:
# Float 32 tensor => default tensor datatype is float32
# float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type (cpu or cuda(gpu))
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [ ]:
# float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
result = float_16_tensor * float_32_tensor
result, result.dtype

(tensor([ 9., 36., 81.]), torch.float32)

### Getting information from tensors

**shape** - what shape is the tensor? (some operations require specific shape rules)

**dtype** - what datatype are the elements within the tensor stored in?

**device** - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int32), torch.int32)

In [ ]:
result = int_32_tensor * float_32_tensor
result, result.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [ ]:
#  Manipulating Tensors (tensor operations)
# 1. Addition
# 2. Subtraction
# 3. Multiplication (element - wise)
# 4. Division
# 5. Matrix multipication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#  try out PyTorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multipication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication
2. Matric multiplication (dot product) -> most common operation in neural networks

There are two main rules that performing matrix multiplication needs to satisfy
1. The **inner dimension** must match
2.

In [ ]:
# Element-wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
# Matric multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep leaning: shape errors

In [ ]:
# shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])
# torch.mm is the same as torch.matmul (it's an alias)
# torch.mm(tensor_A, tensor_B)

## To fix our tensor shape issues. we can manipulate the shape of one of our tensors using 'transpose'

A '**transpose**' switches the axes or dimensions of a given tensor

default torch is **float64**

In [ ]:
tensor_B = tensor_B.T

In [ ]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#  Find the mean -> note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#  find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> return index position
x.argmax()

tensor(9)

In [ ]:
# Find the position in tensor that has the maximun value with argmax() -> return index position
x.argmin()

tensor(0)

In [ ]:
# min. max
x[0], x[9]

(tensor(0), tensor(90))

### Reshaping, stacking, sqeezing and unsquezzing tensors

* Reshaping -> reshapes an input tensor to a define shape
* View -> Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -> combine multiple tensors on top of each other (vstack) or side by side (hstack)
*Squeeze - remove all '1' dimentions from a tensor
* Unsqueeze - add a '1' dimention to a target tensor
* Permute - Return a view of the input with permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimentions
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing z -> changing x (because a view of a tensor shares the same memory as the original input)

In [ ]:
z[:, 0] = 1
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Squeeze -> remove all single dimention
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze, x_squeeze.shape, x_reshaped.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([9]))

In [ ]:
# torch.unsqueeze() -> add a single dimention to a target tensor at a specific dimention
print(f"Previous target: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

# Add an extra dimention with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print('Unsqueeze: ')
x_unsqueezed, x_unsqueezed.shape

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Unsqueeze: 


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# torch.permute - rearranges the dimentions of a target tensor in a specify order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color_channel]

# Permute the original tensor to rearrange the axis ot dims order
# 2 =>color_channel, 0 => width, 1 => height
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


One of the most common errors in deep learning: shape

In [ ]:
x_original[0, 0, 0] = 123456
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(123456.), tensor(123456.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to index with Numpy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle backet (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner backet (last dim)
x[0][1][1]

tensor(5)

In [ ]:
# You can also use ":" to select "all" of a target dimention
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get allvalues of 0th and 1st dimentions but only index 1 and 2 dimention
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimentions but only the 1 index value and 2nd dimention
x[:, 1, 1]


tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimention and all values of 2nd dimention
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#  index on x so that it return 9
x[0, 2, 2], x[0][2][2]

(tensor(9), tensor(9))

In [ ]:
#  index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors & Numpy

Numpy is a popular scientificPython numerical computing library.

Pytorch has functionality to interact with it.

* Data in Numpy, want tn Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
#  Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor_bef = torch.from_numpy(array) # float64 -> default value when converting numpy to torch unless specified
tensor_aft = torch.from_numpy(array).type(torch.float32)
array, array.dtype, tensor_bef, tensor_aft, tensor_aft.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# change the value of an array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1, 2, 3]))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the value of tensor, what will this do to `numpy`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random number -> tensor operations -> update random numbers to try and make them better representations of the date -> agai -> again -> again...`

to reduce the randoness in neural network and Pytorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randoness

In [ ]:
import torch

# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1862, 0.8846, 0.1901, 0.4358],
        [0.2358, 0.4075, 0.0799, 0.5252],
        [0.8103, 0.2567, 0.5248, 0.3784]])
tensor([[0.7836, 0.8060, 0.1711, 0.6822],
        [0.7678, 0.1090, 0.2005, 0.7554],
        [0.6886, 0.6679, 0.2240, 0.9249]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#  Let's make some random but reproducible tensors
import torch

#  set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##  Running temsors and pytorch object on the GPUs(and making faster computation)

GPUs = faster computation on numbers thanks to CUDA + NVIDI hardware + pytorch working behind the scene

### Getting a GPU
1. use googlecolab
2. get your own GPU
3. cloud computing

for 2,3 pytorch + gpu driver (CUDA) takes a little bit of setting up, to do this, refer to pytorch setting documentation

In [ ]:
!nvidia-smi

Sun Sep  3 08:41:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##  2. check for GPU access with pytorch

In [ ]:
#  2. check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

For Pytorch since it's capable of urnning compute of running on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g., run on GPU if available, else default to CPU

In [ ]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using GPU results is faster for computations

In [ ]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu
# result :tensor([1, 2, 3], device='cuda:0') => 0 is an index for cuda device that we use

tensor([1, 2, 3], device='cuda:0')

**Numpy only work with CPU** => we need to move tensors back to CPU

### 4. Moving tensors back to the CPU


In [ ]:
# if tensors is on GPU, can't transform it to numpy
# tensor_on_gpu.numpy() -> this will cause an error as the device is wrong!!!
# Error: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the GPU tensor with umPy issue, we can first set it to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

# **Exercise & Extra-curriculum**