# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A, random_tensor_A.shape

(tensor([[0.1688, 0.2237, 0.9437, 0.4843, 0.6103, 0.7640, 0.8390],
         [0.7738, 0.2268, 0.0338, 0.0449, 0.3884, 0.8347, 0.3163],
         [0.2483, 0.1147, 0.7743, 0.0900, 0.8024, 0.4025, 0.6788],
         [0.9113, 0.3526, 0.4616, 0.1894, 0.5480, 0.5889, 0.3408],
         [0.9970, 0.4277, 0.8661, 0.1654, 0.6715, 0.7603, 0.2962],
         [0.0844, 0.3727, 0.4474, 0.4769, 0.0014, 0.0676, 0.2912],
         [0.9012, 0.9583, 0.1196, 0.3659, 0.1239, 0.0275, 0.0948]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [79]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7)
random_tensor_BT = torch.t(random_tensor_B)
# random_tensor_BT, random_tensor_BT.shape
# Perform matrix multiplication
result_mul = torch.mm(random_tensor_A, random_tensor_BT)
result_mul

tensor([[2.6268],
        [1.2580],
        [2.1759],
        [1.9867],
        [2.4924],
        [1.2164],
        [1.5523]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [65]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.t(torch.rand(1, 7))

# Matrix multiply tensors
result_mul2 = torch.mm(random_tensor_C, random_tensor_D)

# print(random_tensor_C, random_tensor_D)
print(result_mul2, result_mul2.shape)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [60]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
# torch.cuda.manual_seed(RANDOM_SEED_GPU)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [69]:
# Set random seed
# Check for access to GPU
is_cuda = torch.cuda.is_available()
device  = 'cuda' if is_cuda else 'cpu'
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED_GPU)
random_tensor_GPU_A  = torch.rand(2, 3).to(device)

torch.manual_seed(RANDOM_SEED_GPU)
random_tensor_GPU_B = torch.rand(2, 3).to(device)

print(random_tensor_GPU_A, random_tensor_GPU_A.device, ' :\n', random_tensor_GPU_B, random_tensor_GPU_B.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0  :
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [71]:
# Perform matmul on tensor_A and tensor_B
result_mul3 = torch.mm(random_tensor_GPU_A, torch.t(random_tensor_GPU_B))
result_mul3, result_mul3.device, result_mul3.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 device(type='cuda', index=0),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [72]:
# Find max
val_max = torch.max(result_mul3)
# Find min
val_min = torch.min(result_mul3)
val_max, val_min

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [73]:
# Find arg max
max_pos = result_mul3.argmax()
# Find arg min
min_pos = result_mul3.argmin()
max_pos, min_pos

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [76]:
# Set seed
RANDOM_SEED2 = 7

torch.manual_seed(RANDOM_SEED2)
# Create random tensor
random_tensor_F = torch.rand(1, 1, 1, 10)

# Remove single dimensions
new_random_tensor_F = torch.squeeze(random_tensor_F)

# Print out tensors and their shapes
print(random_tensor_F, random_tensor_F.shape, ' :\n', new_random_tensor_F, new_random_tensor_F.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])  :
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
